version: "3.8"
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    image: custom-jenkins:latest
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home:



#The jenkins service now uses your custom-built image (custom-jenkins:latest) instead of the default jenkins/jenkins:lts.
#Docker Socket Mount:This allows Jenkins (inside the container) to control Docker on your host machine, so it can build and run other containers for your pipeline.
