version: "3.8"

services:
  app:
    image: ${DOCKER_USERNAME:-your-username}/plantbot:staging
    container_name: plantbot-staging
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=staging
      - PORT=80
    restart: unless-stopped
    networks:
      - staging-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  staging-network:
    driver: bridge
