version: "3.8"

services:
  cypress:
    image: cypress/included:latest
    working_dir: /e2e
    environment:
      - CYPRESS_BASE_URL=https://your-staging-domain.com  # Update with your actual staging URL
    volumes:
      - ./cypress:/e2e/cypress
      - ./cypress.config.ts:/e2e/cypress.config.ts
    command: run --browser chrome  # Run tests in headless mode by default
