// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lssvxuzyzkrdkbnsceit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxzc3Z4dXp5emtyZGtibnNjZWl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4ODE4ODksImV4cCI6MjA2NTQ1Nzg4OX0.o24HPmcIXDg3KZuHtXCeg_sffLw0Cr9yUlpYFyPyRZI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);